### ISSUE TITLE
Install issue using anaconda

### ISSUE THREAD

**Issue by chan-y-park** [kengz/openai_lab#113]
Hi,

I tried installing openai_lab on an anaconda environment using bin/setup.py, but it did not work because the setup script runs ```sudo python3``` which invokes the system python rather than the anaconda python.

In the end I was able to run open_ai by installing all the dependencies by hand, but I think it would be better not to ask for users to use ```sudo``` during running the setup script so that a user without a superuser privilege can install openai_lab and that the installation will not interfere with the system.

**Comment by kengz** [comment]
Hi, thanks for the suggestions!

The installation is definitely something we'll be improving.
After the feedback from other users yesterday it seems useful to have several installation channels:
- plain installation (system python)
- conda (seem to be a quite popular option)
- Docker (much stabler for better quickstart, but with a performance speed tradeoff)

Added to the [roadmap](https://github.com/kengz/openai_lab/projects/2) and we'll get to this soon as we can.

**Comment by kengz** [comment]
Addressed in [release v1.0.3](https://github.com/kengz/openai_lab/releases/tag/v1.0.3)
